(async () => {
  let checkCount = 0;
  const check = (ok, message) => { checkCount += 1; if (!ok) throw new Error(message); };
  const tick = async () => {
    for (let attempt = 0; attempt < 150 && document.getElementById('private-root').getAttribute('aria-busy') === 'true'; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
    check(document.getElementById('private-root').getAttribute('aria-busy') === 'false', 'Refresh completed');
  };
  const active = () => document.querySelector('.market-panel:not([hidden])');
  const visible = () => [...active().querySelectorAll('.action-card:not([hidden])')];
  const search = (text) => {
    const input = active().querySelector('input');
    input.value = text; input.dispatchEvent(new Event('input', {bubbles: true}));
  };
  check(window.__auditOffset === 0, 'Test clock initialized');
  check(document.querySelectorAll('.action-card').length === 4, 'Inactive market rendered eagerly');
  check(visible().length === 3, 'Default top three');
  search('alpha');
  check(visible().length === 1 && visible()[0].dataset.ticker === 'ALPHA', 'Search must include non-top rows');
  check(new URL(location.href).searchParams.get('q') === 'alpha', 'Search URL restoration');
  search('not-a-real-ticker');
  check(!active().querySelector('.filter-empty').hidden, 'No-results guidance');
  active().querySelector('.reset-filters').click();
  check(visible().length === 4 && document.activeElement.type === 'search', 'Reset and focus');
  const sort = active().querySelector('select');
  sort.value = 'change'; sort.dispatchEvent(new Event('change'));
  check(visible().map((node) => node.dataset.ticker).join(',') === 'BETA,ALPHA,005930.KS,MISSING', 'Sort numeric changes, missing last');
  const missing = visible().find((node) => node.dataset.ticker === 'MISSING');
  check(missing.querySelector('.price-line strong').textContent === '-', 'Missing price is not zero');
  check(missing.querySelector('.signal strong').textContent === '-', 'Missing confidence is not zero');
  check(!missing.querySelector('img'), 'Display names must remain escaped text');
  document.querySelector('#private-tabs [data-target="us"]').click();
  check(active().dataset.market === 'us', 'Market switch');
  search('NVDA');
  const detail = visible()[0].querySelector('details');
  detail.open = true;
  detail.querySelector('summary').focus();
  const sourceRun = active().querySelector('.source-meta').textContent;
  window.__auditOffset = 3 * 60 * 60 * 1000;
  window.dispatchEvent(new Event('pageshow'));
  check(active().querySelector('.market-health').textContent === '주문 전 실시간 확인', 'Expiry clock and health badge');
  check(active().dataset.market === 'us' && active().querySelector('input').value === 'NVDA', 'Expiry keeps market and search');
  check(visible()[0].querySelector('details').open, 'Expiry keeps disclosure state');
  check(document.activeElement.tagName === 'SUMMARY', 'Expiry keeps keyboard focus');
  check(visible()[0].dataset.readiness !== 'READY', 'Expired data cannot remain executable');
  check(new URL(location.href).searchParams.get('market') === 'us', 'Market URL sync');
  const originalFetch = window.fetch;
  window.fetch = async () => { throw new Error('테스트 연결 실패'); };
  document.getElementById('strategy-refresh').click();
  await tick();
  check(document.getElementById('private-status').classList.contains('error'), 'Refresh error feedback');
  check(active().querySelector('.source-meta').textContent === sourceRun, 'Refresh failure keeps previous snapshot');
  check(!document.getElementById('strategy-refresh').disabled, 'Retry remains available');
  window.fetch = originalFetch;
  document.getElementById('strategy-refresh').click();
  await tick();
  check(!document.getElementById('private-status').classList.contains('error'), 'Retry recovers');
  check(active().dataset.market === 'us' && active().querySelector('input').value === 'NVDA', 'Refresh keeps selection');
  check(document.querySelectorAll('input[type="search"]').length === 1, 'Refreshed inactive market stays lazy');
  const payload = await (await originalFetch(document.body.dataset.strategyUrl)).json();
  const market = payload.markets.us;
  market.source = {status: 'success'};
  market.decision_ready = market.quality.decision_ready = market.guardrails.decision_ready = true;
  const future = new Date(Date.now() + 3600000).toISOString();
  market.guardrails.valid_until = future;
  Object.assign(market.universe_coverage, {expected_analysis_count: 4, analysis_total_count: 4, analysis_successful_count: 4, missing_analysis_count: null});
  market.rows.forEach((row) => Object.assign(row.quality, {investor_state: 'READY', execution_ready: true, generated_in_current_run: true, row_valid_until: future}));
  window.fetch = async () => ({ok: true, json: async () => payload});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].dataset.readiness === 'RECHECK', 'Missing coverage must not count as zero');
  market.universe_coverage.missing_analysis_count = 0;
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].dataset.readiness === 'READY', 'Complete ready contract remains supported');
  const malformed = structuredClone(payload);
  malformed.markets.us.integrated_report = {structured_report: {strategies: {}}};
  window.fetch = async () => ({ok: true, json: async () => malformed});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(document.getElementById('private-status').classList.contains('error'), 'Malformed nested report feedback');
  check(visible()[0].dataset.readiness === 'READY', 'Malformed refresh restores the previous snapshot');
  window.fetch = originalFetch;
  return {status: 'PASSED', width: innerWidth, checks: checkCount, url: location.search};
})()
