(async () => {
  let checkCount = 0;
  const check = (ok, message) => { checkCount += 1; if (!ok) throw new Error(message); };
  const tick = async () => {
    for (let attempt = 0; attempt < 150 && document.getElementById('private-root').getAttribute('aria-busy') === 'true'; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
    check(document.getElementById('private-root').getAttribute('aria-busy') === 'false', 'Refresh completed');
  };
  const active = () => document.querySelector('.market-panel:not([hidden])');
  const visible = () => [...active().querySelectorAll('.action-card:not([hidden])')];
  const checkDistribution = () => {
    const directions = {};
    active().querySelectorAll('.action-card .private-action').forEach((node) => { directions[node.dataset.direction] = (directions[node.dataset.direction] || 0) + 1; });
    active().querySelectorAll('.overview-stat').forEach((node) => check(Number(node.querySelector('strong').textContent) === (directions[node.dataset.direction] || 0), 'Overview matches actual card direction: ' + node.dataset.direction));
  };
  const search = (text) => {
    const input = active().querySelector('input');
    input.value = text; input.dispatchEvent(new Event('input', {bubbles: true}));
  };
  check(window.__auditOffset === 0, 'Test clock initialized');
  check(document.querySelectorAll('.action-card').length === 4, 'Inactive market rendered eagerly');
  check(visible().length === 4, 'Default shows all rows');
  checkDistribution();
  const summaryRows = () => [...active().querySelectorAll('.strategy-summary tbody tr')];
  const planRow = (ticker) => summaryRows().find((row) => row.dataset.ticker === ticker);
  const checkTradePlan = (market) => {
    const unit = market === 'kr' ? '원' : '$';
    const buy = planRow('ALPHA');
    const sell = planRow('BETA');
    const zero = planRow(market === 'kr' ? '005930.KS' : 'NVDA');
    const unavailable = planRow('MISSING');
    check(/\b2\s*주/.test(buy.querySelector('.plan-quantity').textContent), 'Conditional buy exposes two account-sized shares');
    check(/\b3\s*주/.test(sell.querySelector('.plan-quantity').textContent), 'Sell proposal displays its three-share holdings cap');
    check(/\b0\s*주/.test(zero.querySelector('.plan-quantity').textContent), 'Unaffordable one-share purchase remains zero shares');
    check(unavailable.querySelector('.plan-quantity').textContent.includes('산출 보류'), 'Unavailable quantity is distinct from zero shares');
    check(unavailable.querySelector('.plan-price').textContent.includes('범위 미확정'), 'Unavailable price is not a zero-cost trade');
    check(buy.querySelector('.plan-price').textContent.includes(unit), 'Price range uses ' + market + ' native currency');
    check(buy.querySelector('.plan-amount').textContent.includes(unit), 'Trade estimate uses ' + market + ' native currency');
    check(!buy.querySelector('.plan-amount .plan-value').textContent.includes('-'), 'Purchase outflow is shown as a positive spending amount');
    check(buy.querySelector('.plan-amount').textContent.includes('예상 지출'), 'Buy cost has an explicit spending label');
    check(sell.querySelector('.plan-amount').textContent.includes('예상 수령액'), 'Sell proceeds have an explicit receipt label');
    check(buy.querySelector('.plan-price').textContent.includes(market === 'kr' ? '99,000' : '99'), 'Lower entry price remains visible');
    check(buy.querySelector('.plan-price').textContent.includes(market === 'kr' ? '101,500' : '101.5'), 'Upper entry price remains visible');
    check(buy.textContent.includes('조건 충족 시'), 'Conditional quantity is not presented as a current order');
    check(buy.querySelector('.plan-check').textContent.includes('종가·거래량 조건을 모두 확인'), 'Trade plan preserves the declared trigger condition');
    check(buy.querySelector('.plan-check').textContent.includes('<img src=x onerror="alert(1)">'), 'Trade-plan conditions remain inspectable text');
    check(!active().querySelector('.strategy-summary img'), 'Trade-plan conditions render as escaped text');
    const planDetails = buy.querySelector('.plan-details');
    check(planDetails && !planDetails.open, 'Long plan conditions start collapsed');
    check([...buy.querySelectorAll('.plan-check small')].some((node) => !node.closest('details') && node.textContent.includes('조건 충족 시 검토')), 'First plan reason remains visible without expanding conditions');
    planDetails.querySelector('summary').click();
    check(planDetails.open && planDetails.querySelector('.plan-condition').getBoundingClientRect().height > 0, 'Plan disclosure exposes the full conditions');
    check(planDetails.textContent.includes('긴 조건의 마지막 확인 문구') && planDetails.textContent.includes('네 번째 조건도 생략하지 않음'), 'Expanded plan preserves long and later conditions');
    check(planDetails.textContent.includes('추가 산출 근거의 마지막 확인 문구'), 'Expanded plan preserves all calculation reasons');
    planDetails.querySelector('summary').click();
    check(!/NaN|undefined|Infinity/.test(active().querySelector('.strategy-summary').textContent), 'Trade-plan cells never leak missing-value placeholders');
    check(document.documentElement.scrollWidth <= innerWidth + 1, 'Strategy plan fits the viewport without page overflow');
  };
  check(summaryRows().length === 4, 'Overview table includes all tickers by default');
  checkTradePlan('kr');
  check(summaryRows().map(row => row.dataset.ticker).join(',') === visible().map(row => row.dataset.ticker).join(','), 'Table and detailed cards have identical order');
  const tableLink = summaryRows()[0].querySelector('button');
  tableLink.click();
  check(document.activeElement.id === tableLink.dataset.detailTarget, 'Table link focuses its detailed strategy');
  document.activeElement.querySelector('.back-to-overview').click();
  check(document.activeElement.classList.contains('strategy-summary'), 'Return to summary retains navigation focus');
  active().querySelector('[data-group-target="HOLDING"]').click();
  search('no-match');
  active().querySelector('[data-direction-target="buy"]').click();
  check(visible().length > 0 && visible().every(row => row.dataset.direction === 'buy'), 'Buy summary filters the entire universe');
  check(active().querySelector('input').value === '' && active().querySelector('[data-group-target="ALL"]').getAttribute('aria-pressed') === 'true', 'Direction selection clears conflicting search and group');
  check(new URL(location.href).searchParams.get('direction') === 'buy', 'Direction deep link');
  check(summaryRows().length === visible().length, 'Table follows direction filter');
  active().querySelector('[data-direction-target="sell"]').click();
  check(visible().length === 1 && visible()[0].dataset.ticker === 'BETA', 'Sell direction is distinct from buy');
  active().querySelector('[data-direction-target="research"]').click();
  check(visible().length === 0 && summaryRows().length === 0 && !active().querySelector('.filter-empty').hidden, 'Zero-count filter is explained');
  active().querySelector('[data-direction-target="all"]').click();
  check(visible().length === 4, 'All directions restores full universe');
  search('alpha');
  check(visible().length === 1 && visible()[0].dataset.ticker === 'ALPHA', 'Search must include non-top rows');
  check(new URL(location.href).searchParams.get('q') === 'alpha', 'Search URL restoration');
  search('not-a-real-ticker');
  check(!active().querySelector('.filter-empty').hidden, 'No-results guidance');
  active().querySelector('.reset-filters').click();
  check(visible().length === 4 && document.activeElement.type === 'search', 'Reset and focus');
  const sort = active().querySelector('select');
  sort.value = 'change'; sort.dispatchEvent(new Event('change'));
  check(visible().map((node) => node.dataset.ticker).join(',') === 'BETA,ALPHA,005930.KS,MISSING', 'Sort numeric changes, missing last');
  const missing = visible().find((node) => node.dataset.ticker === 'MISSING');
  check(missing.querySelector('.price-line strong').textContent === '-', 'Missing price is not zero');
  check(missing.querySelector('.signal strong').textContent === '-', 'Missing confidence is not zero');
  check(!missing.querySelector('img'), 'Display names must remain escaped text');
  active().querySelector('[data-direction-target="sell"]').click();
  document.querySelector('#private-tabs [data-target="us"]').click();
  check(active().dataset.market === 'us', 'Market switch');
  check(active().querySelector('[data-direction-target="all"]').getAttribute('aria-pressed') === 'true', 'Market direction filters are independent');
  checkTradePlan('us');
  search('ALPHA');
  const expiryPlan = planRow('ALPHA').querySelector('.plan-details');
  expiryPlan.querySelector('summary').click();
  expiryPlan.querySelector('summary').focus();
  const expiryPlanId = expiryPlan.dataset.planId;
  window.__auditOffset = 3 * 60 * 60 * 1000;
  window.dispatchEvent(new Event('pageshow'));
  const expiredPlanDetails = planRow('ALPHA').querySelector('.plan-details');
  check(expiredPlanDetails.open && expiredPlanDetails.dataset.planId === expiryPlanId, 'Expiry preserves the expanded plan disclosure');
  check(document.activeElement === expiredPlanDetails.querySelector('summary'), 'Expiry preserves plan disclosure keyboard focus');
  check(expiredPlanDetails.querySelector('.plan-condition').textContent.includes('긴 조건의 마지막 확인 문구'), 'Full plan conditions remain available after expiry');
  check(planRow('ALPHA').querySelector('.plan-status').textContent.includes('현재 주문 없음'), 'Expanded expired plan remains noncurrent');
  window.__auditOffset = 0;
  window.dispatchEvent(new Event('pageshow'));
  search('NVDA');
  document.querySelector('#private-tabs [data-target="kr"]').click();
  check(visible().length === 1 && visible()[0].dataset.ticker === 'BETA', 'KR direction selection survives market switch');
  document.querySelector('#private-tabs [data-target="us"]').click();
  check(active().querySelector('input').value === 'NVDA', 'US search survives market switch');
  const detail = visible()[0].querySelector('details');
  detail.open = true;
  detail.querySelector('summary').focus();
  const sourceRun = active().querySelector('.source-meta').textContent;
  window.__auditOffset = 3 * 60 * 60 * 1000;
  window.dispatchEvent(new Event('pageshow'));
  check(active().querySelector('.market-health').textContent === '주문 전 실시간 확인', 'Expiry clock and health badge');
  check(active().dataset.market === 'us' && active().querySelector('input').value === 'NVDA', 'Expiry keeps market and search');
  check(visible()[0].querySelector('details').open, 'Expiry keeps disclosure state');
  check(document.activeElement.tagName === 'SUMMARY', 'Expiry keeps keyboard focus');
  check(visible()[0].dataset.readiness !== 'READY', 'Expired data cannot remain executable');
  check(new URL(location.href).searchParams.get('market') === 'us', 'Market URL sync');
  search('ALPHA');
  check(/\b2\s*주/.test(planRow('ALPHA').querySelector('.plan-quantity').textContent), 'Expiry preserves the two-share reference proposal');
  check(planRow('ALPHA').querySelector('.plan-quantity').textContent.includes('입력 계좌 기준 검토 수량'), 'Expired quantity is explicitly a reference estimate');
  check(planRow('ALPHA').querySelector('.plan-status').textContent.includes('현재 주문 없음'), 'Expired conditional plan cannot imply a current order');
  check(planRow('ALPHA').querySelector('.plan-status').textContent.includes('재확인'), 'Expired price and account data require rechecking');
  search('NVDA');
  const originalFetch = window.fetch;
  window.fetch = async () => { throw new Error('테스트 연결 실패'); };
  document.getElementById('strategy-refresh').click();
  await tick();
  check(document.getElementById('private-status').classList.contains('error'), 'Refresh error feedback');
  check(active().querySelector('.source-meta').textContent === sourceRun, 'Refresh failure keeps previous snapshot');
  check(!document.getElementById('strategy-refresh').disabled, 'Retry remains available');
  window.fetch = originalFetch;
  document.getElementById('strategy-refresh').click();
  await tick();
  check(!document.getElementById('private-status').classList.contains('error'), 'Retry recovers');
  check(active().dataset.market === 'us' && active().querySelector('input').value === 'NVDA', 'Refresh keeps selection');
  check(document.querySelectorAll('input[type="search"]').length === 1, 'Refreshed inactive market stays lazy');
  const payload = await (await originalFetch(document.body.dataset.strategyUrl)).json();
  const market = payload.markets.us;
  market.source = {status: 'success'};
  market.decision_ready = market.quality.decision_ready = market.guardrails.decision_ready = true;
  const future = new Date(Date.now() + 3600000).toISOString();
  market.guardrails.valid_until = future;
  Object.assign(market.universe_coverage, {expected_analysis_count: 4, analysis_total_count: 4, analysis_successful_count: 4, missing_analysis_count: null});
  market.rows.forEach((row) => Object.assign(row.quality, {investor_state: 'READY', execution_ready: true, generated_in_current_run: true, row_valid_until: future}));
  window.fetch = async () => ({ok: true, json: async () => payload});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].dataset.readiness === 'RECHECK', 'Missing coverage must not count as zero');
  market.universe_coverage.missing_analysis_count = 0;
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].dataset.readiness === 'READY', 'Complete ready contract remains supported');
  const stalePlan = market.trade_plan.rows.find((row) => row.ticker === 'NVDA');
  const savedPlan = structuredClone(stalePlan);
  Object.assign(stalePlan, {quantity: 2, phase: 'NOW', status: 'RECHECK', valid_until: future});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].dataset.readiness === 'READY', 'Plan age does not change the independent analysis readiness');
  check(planRow('NVDA').querySelector('.plan-status').textContent.includes('현재 주문 없음'), 'Ready analysis cannot make a stale account plan current');
  check(planRow('NVDA').querySelector('.plan-status').textContent.includes('재확인'), 'Stale plan has its own recheck state');
  Object.assign(stalePlan, {status: 'CONDITIONAL', valid_until: savedPlan.valid_until});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].dataset.readiness === 'READY', 'Analysis stays independently ready when only the plan expires');
  check(planRow('NVDA').querySelector('.plan-status').textContent.includes('현재 주문 없음'), 'Expired plan cannot become current even with a ready analysis and fresh account');
  check(planRow('NVDA').querySelector('.plan-status').textContent.includes('재확인'), 'Plan expiry requires its own recheck');
  Object.assign(stalePlan, savedPlan);
  const beforeDirection = visible()[0].querySelector('.private-action').dataset.direction;
  const beforeRole = visible()[0].dataset.group;
  market.reference_report = {lineage: {current_action_cards_enriched: false}, structured_report: {strategies: [{ticker: 'NVDA', portfolio_role: 'discovery', rank: 1, thesis: {stance: 'SELL'}}]}};
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].querySelector('.private-action').dataset.direction === beforeDirection, 'Reference report cannot overwrite current direction');
  check(visible()[0].dataset.group === beforeRole, 'Reference report cannot overwrite membership');
  checkDistribution();
  const canonical = market.rows.find((row) => row.ticker === 'NVDA');
  canonical.thesis = {stance: 'HOLD', confidence: 0.6,
    entry_conditions: ['Review source evidence. '.repeat(12) + 'Mandatory reward/risk >= 1.5.', 'Close above 100', 'Relative volume >= 1.2', 'Official filing must confirm guidance.'],
    observation_conditions: ['Close below 90: reduce half the position'],
    invalidation_conditions: ['Close below 90', 'Volume collapse', 'Guidance cut', 'Cancel unfilled orders after expiry.'], invalidation_action: 'Close below 90: reduce half the position',
    rationale: ['Cash conversion remains unverified; await the next filing.']};
  document.getElementById('strategy-refresh').click();
  await tick();
  check(visible()[0].querySelectorAll('.condition-block.risk p')[1].textContent.includes('reduce half the position'), 'Canonical risk response survives without current Work');
  check(visible()[0].querySelector('.card-rationale').textContent.includes('Cash conversion remains unverified'), 'Canonical rationale survives without current Work');
  check(!visible()[0].querySelector('details').textContent.includes('Work 전체'), 'Raw analysis is not mislabeled as Work');
  check(visible()[0].querySelector('details').textContent.includes('원분석 관찰 목록 · 진입 신호와 구별'), 'Mixed observations have a separate label');
  const entryText = visible()[0].querySelector('.condition-block p').textContent;
  check(entryText.includes('Mandatory reward/risk >= 1.5.') && entryText.includes('Official filing must confirm guidance.'), 'Long and fourth entry conditions are not silently omitted');
  check(visible()[0].querySelector('.condition-block.risk p').textContent.includes('Cancel unfilled orders after expiry.'), 'Fourth invalidation condition remains visible');
  const malformed = structuredClone(payload);
  malformed.markets.us.integrated_report = {structured_report: {strategies: {}}};
  window.fetch = async () => ({ok: true, json: async () => malformed});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(document.getElementById('private-status').classList.contains('error'), 'Malformed nested report feedback');
  check(visible()[0].dataset.readiness === 'READY', 'Malformed refresh restores the previous snapshot');
  const sizingAccountTimestamp = market.trade_plan.account_asof;
  const sizingAccountNote = active().querySelector('.plan-source-note').textContent;
  const originalReceipt = market.freshness_receipt;
  market.trade_plan.account_asof = null;
  market.freshness_receipt = {...(originalReceipt || {}), account_as_of: '2001-02-03T04:05:00+09:00'};
  window.fetch = async () => ({ok: true, json: async () => payload});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(active().querySelector('.plan-source-note').textContent.includes('수량 기준 계좌 확인 불가'), 'A plan without its own account timestamp is explicitly unverified');
  check(!active().querySelector('.plan-source-note').textContent.includes('2001'), 'A receipt timestamp cannot substitute for a missing plan account timestamp');
  market.trade_plan.account_asof = sizingAccountTimestamp;
  document.getElementById('strategy-refresh').click();
  await tick();
  check(active().querySelector('.plan-source-note').textContent === sizingAccountNote, 'Restoring the plan account timestamp restores its original source note');
  check(!active().querySelector('.plan-source-note').textContent.includes('확인 불가') && !active().querySelector('.plan-source-note').textContent.includes('2001'), 'Verified sizing source remains distinct from the unrelated receipt');
  if (originalReceipt === undefined) delete market.freshness_receipt;
  else market.freshness_receipt = originalReceipt;
  const legacy = structuredClone(payload);
  delete legacy.markets.us.trade_plan;
  window.fetch = async () => ({ok: true, json: async () => legacy});
  document.getElementById('strategy-refresh').click();
  await tick();
  check(!document.getElementById('private-status').classList.contains('error'), 'Legacy strategy without a trade plan remains readable');
  check(planRow('NVDA').querySelector('.plan-quantity').textContent.includes('산출 보류'), 'Legacy quantity is unavailable rather than fabricated');
  check(planRow('NVDA').querySelector('.plan-price').textContent.includes('범위 미확정'), 'Legacy data cannot invent an entry price');
  check(planRow('NVDA').querySelector('.plan-amount').textContent.includes('미확정'), 'Legacy data cannot invent a trade amount');
  legacy.markets.us.freshness_receipt = {account_as_of: '2026-10-01T00:08:00+09:00'};
  document.getElementById('strategy-refresh').click();
  await tick();
  check(active().querySelector('.plan-source-note').textContent.includes('수량 기준 계좌 확인 불가'), 'Unverified quantity account does not fall back to a different account receipt');
  check(!active().querySelector('.plan-source-note').textContent.includes('00:08'), 'Receipt account timestamp is not advertised as the sizing input');
  window.fetch = originalFetch;
  return {status: 'PASSED', width: innerWidth, checks: checkCount, url: location.search};
})()
